// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListFeeds(arg1) {
  return window['go']['feeds']['Feeds']['ListFeeds'](arg1);
}
