// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {feeds} from '../models';
import {context} from '../models';

export function AddFeed(arg1:feeds.Feed):Promise<void>;

export function ListFeeds():Promise<Array<feeds.Feed>>;

export function Startup(arg1:context.Context):Promise<void>;
