// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFeed(arg1) {
  return window['go']['feeds']['Feeds']['AddFeed'](arg1);
}

export function ListFeeds() {
  return window['go']['feeds']['Feeds']['ListFeeds']();
}

export function Startup(arg1) {
  return window['go']['feeds']['Feeds']['Startup'](arg1);
}
