// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {feeds} from '../models';

export function ListFeeds(arg1:string):Promise<Array<feeds.Feed>>;
