// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function Echo(arg1:string):Promise<string>;

export function GetArticles():Promise<Array<app.Article>>;

export function Startup(arg1:context.Context):Promise<void>;
